Upload file
Tinggaard/P2 pull request #37
Opened 2023-04-27 10:39 UTC by Maxnm47

2023-04-27 10:55 UTC, Tinggaard commented on src/public/client.js
> +          'Content-Type': 'application/json', // set the Content-Type header
Massivt god kommentar.

2023-04-27 11:14 UTC, enevoldsen1oo approved these changes
Super nice working very fine :)

2023-04-27 11:15 UTC, enevoldsen1oo requested changes
Please make it work for me also :)

2023-04-27 11:16 UTC, Tinggaard requested changes
Lav en indikation på at filen er uploadet. Og lav CSS pænt.

2023-05-01 10:49 UTC, Tinggaard requested changes

2023-05-01 10:49 UTC, Tinggaard commented on src/public/client.js
> +// });
nani?!?

2023-05-01 10:49 UTC, Tinggaard commented on src/public/index.html
> +        <!-- <input type="button" value="Upload" class="fileSendButtonClass" id="fileSendButton" /> -->
why is dis here?

2023-05-01 10:58 UTC, Maxnm47 commented on src/public/index.html
> +        <!-- <input type="button" value="Upload" class="fileSendButtonClass" id="fileSendButton" /> -->
Fordi jeg elsker mænd

2023-05-01 10:59 UTC, Maxnm47 commented on src/public/client.js
> +// });
fordi jeg er semi-bisexual, jeg kan kun lide mænd

2023-05-01 10:59 UTC, Tinggaard approved these changes

2023-05-01 11:35 UTC, enevoldsen1oo approved these changes
Yes, I, Martin hereby approve these changes. For I like them

2023-05-01 11:35 UTC, merged